#!/usr/bin/env bash

action "deploy" "Deploy application from ${shared_path}"
action "new {project}" "Create a new tmux project configuration named {project}"
action "edit {project}" "Edit a tmux project configuration named {project}"
action "copy {projecta} {projectb}"\
  "Copy {projecta} configuration to {projectb}, creating {projectb} if missing."
action "rm {project}" "Remove {project} configuration files"
action "implode {project}" "Remove all ~/.bdsm/mux/ {project} configuration files."
action "list" "List all mux projects"
action "info" "List all mux projects with configurations"
action "info {project}" "Display configuration for {project}"
action "open {project}" "Open or switch to {project} in a tmux session"

show_help
